//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrpanoCMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotspot
    {
        public int Id { get; set; }
        public int FkPanoramaId { get; set; }
        public int FkUserId { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string Content { get; set; }
        public double Coordinate_X { get; set; }
        public double Coordinate_Y { get; set; }
    }
}
